# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Historial.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(585, 471)
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(40, 70, 481, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(40, 320, 501, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.btnVer = QtWidgets.QPushButton(Form)
        self.btnVer.setGeometry(QtCore.QRect(130, 360, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(10)
        self.btnVer.setFont(font)
        self.btnVer.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.btnVer.setObjectName("btnVer")
        self.btnEliminar = QtWidgets.QPushButton(Form)
        self.btnEliminar.setGeometry(QtCore.QRect(340, 360, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(10)
        self.btnEliminar.setFont(font)
        self.btnEliminar.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.btnEliminar.setObjectName("btnEliminar")
        self.tableRegistros = QtWidgets.QTableWidget(Form)
        self.tableRegistros.setGeometry(QtCore.QRect(110, 100, 371, 211))
        self.tableRegistros.setObjectName("tableRegistros")
        self.tableRegistros.setColumnCount(0)
        self.tableRegistros.setRowCount(0)
        self.llbtitulohistorial = QtWidgets.QLabel(Form)
        self.llbtitulohistorial.setGeometry(QtCore.QRect(130, 20, 321, 51))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(12)
        self.llbtitulohistorial.setFont(font)
        self.llbtitulohistorial.setObjectName("llbtitulohistorial")
        self.btnvolverhistorial = QtWidgets.QPushButton(Form)
        self.btnvolverhistorial.setGeometry(QtCore.QRect(240, 420, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(10)
        self.btnvolverhistorial.setFont(font)
        self.btnvolverhistorial.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.btnvolverhistorial.setObjectName("btnvolverhistorial")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnVer.setText(_translate("Form", "Ver"))
        self.btnEliminar.setText(_translate("Form", "Eliminar"))
        self.llbtitulohistorial.setText(_translate("Form", "HISTORIAL DE REGISTROS"))
        self.btnvolverhistorial.setText(_translate("Form", "VOLVER"))
